### Create edge
POST http://localhost:8080/edge
Content-Type: application/json
Accept: application/json

{
  "fromId": 1,
  "toId": 2
}

### Get all edges
GET http://localhost:8080/edge
Content-Type: application/json
Accept: application/json

### Get edge by id
GET http://localhost:8080/edge/4
Content-Type: application/json
Accept: application/json

### Delete edge by id
DELETE http://localhost:8080/edge/1
Content-Type: application/json
Accept: application/json

### Get tree by fromId
GET http://localhost:8080/tree/1
Content-Type: application/json
Accept: application/json